version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080
    networks:
      - my_network
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "7000:5000"
    networks:
      - my_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
networks:
  my_network:
    driver: bridge